printer:
  port: 'COM5'
  baud: 38400
  always_cut: false
  image:
    rotate: 0
    rotate_to_fit: true
    rotate_to_fit_threshold_factor: 3
  text:
    format: 'debug'
  url:
    show_qr: true
    reference_urls: true
  cooldown_ms:
    message: 0
    image: 1000
security:
  allow_unauthenticated: true
  text_limit: 1000