printer:
  port: '/dev/ttyUSB0'
  baud: 38400
  always_cut: false
  image:
    rotate: 0
    rotate_to_fit: true
    rotate_to_fit_threshold_factor: 3
    max_width: 512
  text:
    template: 'debug'
    allow_custom_template: true
  url:
    show_qr: true
    reference_urls: true
  cooldown_ms:
    message: 0
    image: 1000
security:
  allow_unauthenticated: false
  text_limit: 1000
  valid_api_keys:
   - "koekje"